### ISSUE TITLE
Include wait_for_update on the setDefaultConsent Call

### ISSUE THREAD

**Issue by Zhankevich** [vallonic/consent-studio-gtm-template#1]
When reviewing your template, we've noticed that the `setDefaultConsentState` call does not include the [wait_for_update](https://developers.google.com/tag-platform/tag-manager/templates/api#setdefaultconsentstate) option. This is required for any asynchronous consent management script load to delay tag execution.

**Comment by thierrymaasdam** [comment]
Thank you for your input, @Zhankevich. I have just added the `wait_for_update` option to the function call and set it to 500 ms.

**Comment by Zhankevich** [comment]
This is great. Also to apply this changes sha in the [metadata.yaml](https://github.com/vallonic/consent-studio-gtm-template/blob/main/metadata.yaml) need to be updated.

**Comment by thierrymaasdam** [comment]
Will do, @Zhankevich!

**Comment by thierrymaasdam** [comment]
The metadata file has been updated in commit https://github.com/vallonic/consent-studio-gtm-template/commit/f0703051432713da8febba5208071d3a7de397f2, @Zhankevich. Is it correct that the versioning should be in descending order?

**Comment by thierrymaasdam** [comment]
Hi @Zhankevich, could you please advise on our status towards getting accepted in to the Tag Template Gallery and the resolving of these issues? We're looking forward to it as we continue to build our tool! :-)

**Comment by Zhankevich** [comment]
This template is available in GTM Gallery, see  https://tagmanager.google.com/gallery/#/owners/vallonic/templates/consent-studio-gtm-template

**Comment by thierrymaasdam** [comment]
Thanks for letting me know, @Zhankevich! If you would be so kind as to answer one more question, what would be necessary for us to be added in Google's list of known CMP providers? I look forward to hearing from you.

**Comment by Zhankevich** [comment]
There's information on how to join at the bottom of the CMP Partner Program website here: https://cmppartnerprogram.withgoogle.com/

**Comment by thierrymaasdam** [comment]
Thanks, @Zhankevich. This is great; I have just requested our developer ID to later fill in the partner request form.

**Comment by thierrymaasdam** [comment]
Hi @Zhankevich, 

We have updated our GTM tag a few times over the past months. As far as we believe, we have implemented the correct format to notify your systems of these updates via the `metadata.yml` file. However, in the GTM Community Gallery, the last update date displays June 8th. We have published an update yesterday and on July 7th. I understand that the propagation may take a few days, but since the previous update doesn't show in the gallery, I would like to confirm with you that we are not doing anything wrong. I look forward to hearing from you! Thank you.

P.S.: is this the correct way to be in touch you and/or the GTM Gallery team? If you have a system in place for support inquiries like these, I'd be happy to adapt.
